version: '3.8'
services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017" # 로컬 포트 27017을 컨테이너의 27017 포트에 매핑
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}